# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
author: John Doe
language:
timezone:

feed:
  type: atom
  path: feed
  limit: 0
  content: true

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://elbauldelprogramador.comhttp://fdsaflasdfjadkslfajs
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cards

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:


# Site owner
owner:
  name: Alejandro Alcalde
  slug: alejandro-alcalde
  avatar: alejandro.jpg
  bio: "Graduado en Ingeniería Informática en la ETSIIT, Granada."
  email: contacto@elbauldelprogramador.com
  disqus-shortname: bashyc
  twitter: elbaulp
  facebook: elbauldelprogramador
  google:
    plus: elbauldelprogramador
    analytics: UA-19017085-2
    verify: FBg0GK1_H_PyCw6AD2iaBOclPbEC3LOV8hHXje5276w
    ad-client: ca-pub-9043332344373532
    # ad-slot: 9782918042
    # ad-slot2: 2727042844
    ad-slot3: 2633319248
  bsa: false
  amazon:
    id: elbaudelpro-21
  bing-verify:
  github: algui91
  stackoverflow: 1612432/algui91
  stackcareers: algui91
  linkedin: algui91
