baseURL = "https://elbauldelprogramador.com"
disablePathToLower = false
languageCode = "en-us"
title = "El Baúl del programador"

[permalinks]
  post = "/:slug"

PygmentsCodeFencesGuessSyntax = true
PygmentsCodeFences = true
# color-codes for highlighting derived from this style
PygmentsStyle =              "monokai"
PpygmentsUseClasses=         true

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

menu = "main"

[[menu.main]]
   name =  "Categorías"
   url  = "/categorias/"
[[menu.main]]    
   name =  "Tags"
   url  =  "/tags/"
[[menu.main]]
   name =  "Cursos"
   url  =  "/cursos/"
[[menu.main]]
   name =  "Manuales"
   url  =  "/manuales-gratuitos/"
[[menu.main]]
   name =  "Security Now!"
   url  =  "/category/security-now/"
[[menu.main]]
   name =  "Apoyanos"
   url  =  "/apoyanos/"
[[menu.main]]
   name =  "Colabora"
   url  =  "/colabora/"
[[menu.main]]
   name =  "Contacto"
   url  =  "/contacto/"

[params]
    amp = true # enables amp features

    # define which amp-elements you are using globally, these elements will be included in every page
    ampElements = ["amp-fit-text","amp-accordion","amp-ad","amp-analytics","amp-carousel","amp-iframe","amp-app-banner","amp-dynamic-css-classes","amp-form","amp-fx-flying-carpet","amp-image-lightbox","amp-image","amp-lightbox","amp-sidebar","amp-social-share","amp-sticky-ad","amp-user-notification"]

    themeColor = "#112233" # define a theme color (this will colorize the android address-bar)

    adsensePublisher = "ca-pub-123456789" # required if you want to include google adsense
    googleAnalytics = "UA-123456-78" # required if you want to use google analytics
    appleItunesApp = "app-id=123456789, app-argument=app-name://link/to/app-content" # required if you want to add an app banner with iOS app
    ampManifest = "/amp-manifest.json" # required if you want to add the app-banner feature

    alternatePageName = "HUGO AMP" # alternative name for website structured data
    organisationLogo = "https://gohugohq.com/logo.png" # set organisation logo for structured data
    organisationName = "gohugohq.com" # set organisation name
    organisationAddress = "Some Street 123, 12345 City" # set organisation address

    socialProfiles = ["http://www.facebook.com/your-profile","http://instagram.com/yourProfile","http://www.linkedin.com/in/yourprofile","http://plus.google.com/your_profile"]  # for sameAs in organisation's structured data

    publisherName = "gohugohq.com" # publisher used in article schema
    publisherLogo = "https://gohugo-amp.gohugohq.com/logo-publisher.png" # https://developers.google.com/search/docs/data-types/articles#logo-guidelines
    publisherLogoWidth = 600 # logo width
    publisherLogoHeight = 60 # logo height

    stylesheetRegular = ["/base-styling.css"] # these styles are used when amp is disabled for a specific page
    javascriptRegular = ["/script.js"] # these scripts are used when amp is disabled for a specific page
