baseURL = "https://elbauldelprogramador.com"
disablePathToLower = false
languageCode = "en-us"
title = "El Baúl del programador"
paginate = 12

[permalinks]
post = "/:filename/"
page = "/:filename/"

PygmentsCodeFencesGuessSyntax = true
PygmentsCodeFences = true
# color-codes for highlighting derived from this style
PygmentsStyle =              "monokai"
PpygmentsUseClasses=         true

[taxonomies]
tag = "tags"
category = "categories"
author = "author"

[[menu.main]]
   name =  "Categorías"
   url  = "/categories/"
[[menu.main]]    
   name =  "Tags"
   url  =  "/tags/"
[[menu.main]]
   name =  "Cursos"
   url  =  "/cursos/"
[[menu.main]]
   name =  "Manuales"
   url  =  "/manuales-gratuitos/"
[[menu.main]]
   name =  "Security Now!"
   url  =  "/categories/security-now/"
[[menu.main]]
   name =  "Apoyanos"
   url  =  "/apoyanos/"
[[menu.main]]
   name =  "Colabora"
   url  =  "/colabora/"
[[menu.main]]
   name =  "Contacto"
   url  =  "/contacto/"

[params]
    verify = "FBg0GK1_H_PyCw6AD2iaBOclPbEC3LOV8hHXje5276w"
    gplususer = "ElBauldelProgramador"
    amp = true # enables amp features

    # define which amp-elements you are using globally, these elements will be included in every page
    ampElements = ["amp-fit-text","amp-ad","amp-analytics","amp-image","amp-sidebar","amp-mustache"]

    themeColor = "#112233" # define a theme color (this will colorize the android address-bar)

    adsensePublisher = "ca-pub-9043332344373532" # required if you want to include google adsense
    adSlot = "2633319248"
    googleAnalytics = "UA-19017085-2" # required if you want to use google analytics

    alternatePageName = "El Baúl" # alternative name for website structured data
    organisationLogo = "https://gohugohq.com/logo.png" # set organisation logo for structured data
    organizationName = "El Baúl del Programador" # set organisation name
    organisationAddress = "Some Street 123, 12345 City" # set organisation address

    socialProfiles = ["http://www.facebook.com/elbauldelprogramador",
                      "http://plus.google.com/+elbauldelprogramador",
                      "https://twitter.com/elbaulp",
                      "https://telegram.me/elbauldelprogramador"]  # for sameAs in organisation's structured data

    publisherName = "gohugohq.com" # publisher used in article schema
    publisherLogo = "https://gohugo-amp.gohugohq.com/logo-publisher.png" # https://developers.google.com/search/docs/data-types/articles#logo-guidelines
    publisherLogoWidth = 600 # logo width
    publisherLogoHeight = 60 # logo height

    stylesheetRegular = ["/base-styling.css"] # these styles are used when amp is disabled for a specific page
    javascriptRegular = ["/script.js"] # these scripts are used when amp is disabled for a specific page
